app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns= [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('blog', views.blog, name="blog"),
    path('cart', views.cart, name="cart"),
    path('contact', views.contact, name="contact"),
    path('services', views.services, name="services"),
    path('shop', views.shop, name="shop"),
    path('thank', views.thank, name="thank"),
    path('checkout', views.checkout, name="check"),
    path('messages', views.messages, name = "messages" )

]

furn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]+static(settings.MEDIA_URL, document_name = settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.


class SiteDescription(models.Model):
    fname = models.CharField(max_length=50, blank=False)
    sname = models.CharField(max_length=50, blank=False)
    description = models.TextField(default='')
    image = models.ImageField(upload_to='images', default='profile.png')

    def __int__(self):
        return self.fname

class Products(models.Model):
    name = models.CharField(max_length=50, blank=False)
    price= models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField(default='description')
    image = models.ImageField(upload_to='images', default='profile.png', blank=False)

    def __str__(self):
        return self.name

# class Sofa(models.Model):

class Testimony(models.Model):
    name = models.CharField(max_length=50, blank=False)
    title = models.CharField(max_length=50, blank=False)
    description = models.TextField(default='description')
    image = models.ImageField(upload_to='images',default='profile.png', blank=False)

    def __str__(self):
        return self.name

class ShopItem(models.Model):
    name = models.CharField(max_length=50, blank=False)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='shopItems', default='shopitem.png')

    def __str__(self):
        return self.name

class Team(models.Model):
    name = models.CharField(max_length=50, blank=False)
    # lname = models.CharField(max_length=50, blank=False)
    role = models.CharField(max_length=50, blank=False)
    description = models.TextField(default='')
    image = models.ImageField(upload_to="team", default='profile.png')

    def __int__(self):
        return self.name

class Blog(models.Model):
    name = models.CharField(max_length=50, blank=False)
    title = models.CharField(max_length=100, blank=False)
    date = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='blogs', default='blogs.png')

    def __int__(self):
        return self.name

class Contact(models.Model):
    fname = models.CharField(max_length=50,blank=False)
    lname = models.CharField(max_length=50,blank=False)
    email = models.EmailField(max_length=100, blank=False)
    message = models.TextField(default='')

    def __int__(self):
        return self.email

app/views.py
from django.shortcuts import render, redirect

from app.models import Products, Testimony, ShopItem, Team, Blog, SiteDescription, Contact


# Create your views here.

def index(request):
    product = Products.objects.all()
    test = Testimony.objects.all()
    site = SiteDescription.objects.all()[0]
    context = {'nav': 'index', 'pro': product, "tests": test,
               'site':site}
    return render(request, 'index.html', context)


def contact(request):
    site = SiteDescription.objects.all()[0]

    return render(request, 'contact.html', {'nav': 'contact', 'site':site})


def about(request):
    team = Team.objects.all()
    site = SiteDescription.objects.all()[0]

    return render(request, 'about.html', {'nav': 'about','teams':team, "site":site})


def blog(request):
    blog = Blog.objects.all()
    site = SiteDescription.objects.all()[0]

    return render(request, 'blog.html', {'nav': 'blog', 'blogs':blog, 'site':site})


def checkout(request):
    return render(request, 'checkout.html', {'nav': 'check'})


def services(request):
    product = Products.objects.all()
    site = SiteDescription.objects.all()[0]

    return render(request, 'services.html', {'nav': 'services','pro':product, 'site':site})


def shop(request):
    item = ShopItem.objects.all()
    return render(request, 'shop.html', {'nav': 'shop', 'items':item})


def thank(request):
    return render(request, 'thankyou.html', {'nav': 'thank'})


def cart(request):
    return render(request, 'cart.html', {'nav': 'cart'})

def test(request):
    tests = Testimony.objects.all()
    return render(request, 'testimonials.html', {"test":tests})

def messages(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        message = request.POST.get('message')

        info = Contact(fname=fname, lname=lname, email=email,message=message)
        info.save()
        return redirect('app:contact')

    return redirect('contact')

app/templates/master.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

		<!-- Bootstrap CSS -->
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"  rel="stylesheet">
{#        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/css-layout/1.1.1/css-layout.min.js">#}
		<link href="{% static "css/tiny-slider.css" %}" rel="stylesheet">
		<link href="{% static "css/style.css" %}" rel="stylesheet">
{#        get bootstrap link#}
{#     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"#}
{#           rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"#}
{#           crossorigin="anonymous">#}
		<title>Governor</title>
	</head>

<body>
		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'app:home' %}">Furni<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'app:home' %}">Home</a>
						</li>
						<li><a class="nav-link" href="{% url 'app:shop' %}">Shop</a></li>
						<li><a class="nav-link" href="{% url 'app:about' %}">About us</a></li>
						<li><a class="nav-link" href="{% url 'app:services' %}">Services</a></li>
						<li><a class="nav-link" href="{% url 'app:blog' %}">Blog</a></li>
						<li><a class="nav-link" href="{% url 'app:contact' %}">Contact us</a></li>
					</ul>

					<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
						<li><a class="nav-link" href="#"><img src={% static "images/user.svg" %}></a></li>
						<li><a class="nav-link" href="{% url 'app:cart' %}"><img src={% static "images/cart.svg" %}></a></li>
					</ul>
				</div>
			</div>

		</nav>
		<!-- End Header/Navigation -->
{% block main %}

{% endblock %}
        {% if nav != 'shop' and nav != 'contact' %}
            		<!-- Start Testimonial Slider -->
                <div class="testimonial-section">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-7 mx-auto text-center">
                                <h2 class="section-title">Testimonials</h2>
                            </div>
                        </div>

                        <div class="row justify-content-center">
                            <div class="col-lg-12">
                                <div class="testimonial-slider-wrap text-center">

                                    <div id="testimonial-nav">
                                        <span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
                                        <span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
                                    </div>

                                    <div class="testimonial-slider">
                                        {% for test in tests %}
                                                                            <div class="item">
                                            <div class="row justify-content-center">
                                                <div class="col-lg-8 mx-auto">

                                                    <div class="testimonial-block text-center">
                                                        <blockquote class="mb-5">
                                                            <p>{{ test.description }}</p>
                                                        </blockquote>

                                                        <div class="author-info">
                                                            <div class="author-pic">
                                                                <img src="/media/{{ test.image }}" alt="{{ test.name }}" class="img-fluid">
                                                            </div>
                                                            <h3 class="font-weight-bold">{{ test.name }}</h3>
                                                            <span class="position d-block mb-3">{{ test.title }}</span>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <!-- END item -->
                                        {% endfor %}
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% endif %}





<!-- Start Footer Section -->
		<footer class="footer-section">
			<div class="container relative">

				<div class="sofa-img">
					<img src="{% static 'images/sofa.png' %}" alt="Image" class="img-fluid">
				</div>

				<div class="row">
					<div class="col-lg-8">
						<div class="subscription-form">
							<h3 class="d-flex align-items-center"><span class="me-1"><img src="{% static 'images/envelope-outline.svg' %}" alt="Image" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>

							<form action="#" class="row g-3">
								<div class="col-auto">
									<input type="text" class="form-control" placeholder="Enter your name">
								</div>
								<div class="col-auto">
									<input type="email" class="form-control" placeholder="Enter your email">
								</div>
								<div class="col-auto">
									<button class="btn btn-primary">
										<span class="fa fa-paper-plane"></span>
									</button>
								</div>
							</form>

						</div>
					</div>
				</div>

				<div class="row g-5 mb-5">
					<div class="col-lg-4">
						<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
						<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant</p>

						<ul class="list-unstyled custom-social">
							<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
						</ul>
					</div>

					<div class="col-lg-8">
						<div class="row links-wrap">
							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">About us</a></li>
									<li><a href="#">Services</a></li>
									<li><a href="#">Blog</a></li>
									<li><a href="#">Contact us</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Support</a></li>
									<li><a href="#">Knowledge base</a></li>
									<li><a href="#">Live chat</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Our team</a></li>
									<li><a href="#">Leadership</a></li>
									<li><a href="#">Privacy Policy</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Nordic Chair</a></li>
									<li><a href="#">Kruzo Aero</a></li>
									<li><a href="#">Ergonomic Chair</a></li>
								</ul>
							</div>
						</div>
					</div>

				</div>

				<div class="border-top copyright">
					<div class="row pt-4">
						<div class="col-lg-6">
							<p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a>  Distributed By <a href="https://themewagon.com">ThemeWagon</a> <!-- License information: https://untree.co/license/ -->
            </p>
						</div>

						<div class="col-lg-6 text-center text-lg-end">
							<ul class="list-unstyled d-inline-flex ms-auto">
								<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

					</div>
				</div>

			</div>
		</footer>
		<!-- End Footer Section -->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/tiny-slider.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

app/templates/services.html
{% extends 'master.html' %}
{% load static %}

{% block main %}

		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Services</h1>
								<p class="mb-4">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
								<p><a href="" class="btn btn-secondary me-2">Shop Now</a><a href="#" class="btn btn-white-outline">Explore</a></p>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="hero-img-wrap">
								<img src="{% static 'images/couch.png' %}" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

		

		<!-- Start Why Choose Us Section -->
		<div class="why-choose-section">
			<div class="container">
				
				
				<div class="row my-5">
					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/truck.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Fast &amp; Free Shipping</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/bag.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Easy to Shop</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/support.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>24/7 Support</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/return.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Hassle Free Returns</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/truck.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Fast &amp; Free Shipping</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/bag.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Easy to Shop</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/support.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>24/7 Support</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

					<div class="col-6 col-md-6 col-lg-3 mb-4">
						<div class="feature">
							<div class="icon">
								<img src="{% static 'images/return.svg' %}" alt="Image" class="imf-fluid">
							</div>
							<h3>Hassle Free Returns</h3>
							<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
						</div>
					</div>

				</div>
			
			</div>
		</div>
		<!-- End Why Choose Us Section -->

		<!-- Start Product Section -->
		<div class="product-section pt-0">
			<div class="container">
				<div class="row">

					<!-- Start Column 1 -->
					<div class="col-md-12 col-lg-3 mb-5 mb-lg-0">
						<h2 class="mb-4 section-title">Crafted with excellent material.</h2>
						<p class="mb-4">Donecc vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. </p>
						<p><a href="#" class="btn">Explore</a></p>
					</div> 
					<!-- End Column 1 -->
    					<!-- Start Column 2 -->
                    {% for x in pro %}
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="{% url 'app:cart' %}{% if forloop2 == 2 %} active {% endif %}" >
{#							<img src="{% static 'images/product-1.png' %}" class="img-fluid product-thumbnail">#}
							<img src="/media/{{ x.image }}" class="img-fluid product-thumbnail">
                            <h3 class="product-title">{{ x.name }}</h3>
                            <p><i>{{ x.description }}</i></p>
							<strong class="product-price">Ksh{{ x.price }}</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div>
                    {% endfor %}

{% comment %}					<!-- Start Column 2 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="#">
							<img src="{% static 'images/product-1.png' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Nordic Chair</h3>
							<strong class="product-price">Ksh50.00</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div> 
					<!-- End Column 2 -->

					<!-- Start Column 3 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="#">
							<img src="{% static 'images/product-2.png' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Kruzo Aero Chair</h3>
							<strong class="product-price">Ksh78.00</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div>
					<!-- End Column 3 -->

					<!-- Start Column 4 -->
					<div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
						<a class="product-item" href="#">
							<img src="{% static 'images/product-3.png' %}" class="img-fluid product-thumbnail">
							<h3 class="product-title">Ergonomic Chair</h3>
							<strong class="product-price">Ksh43.00</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div>
					<!-- End Column 4 -->

				</div>
			</div>
		</div>
		<!-- End Product Section -->{% endcomment %}

		
{% comment %}

		<!-- Start Testimonial Slider -->
		<div class="testimonial-section before-footer-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">

							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>

							<div class="testimonial-slider">

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis volutpat dui quis scelerisque.&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{% static 'images/person-1.png' %}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">Maria Jones</h3>
													<span class="position d-block mb-3">CEO, Co-Founder, XYZ Inc.</span>
												</div>
											</div>

										</div>
									</div>
								</div>
								<!-- END item -->

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

{% endcomment %}


		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/tiny-slider.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

app/templates/testimonials.html
{% extends 'master.html' %}
{% block main %}
{% endblock %}

app/templates/thankyou.html
{% extends 'master.html' %}
{% load static %}

{% block main %}
		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Cart</h1>
							</div>
						</div>
						<div class="col-lg-7">
							
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

		

		<div class="untree_co-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center pt-5">
          <span class="display-3 thankyou-icon text-primary">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
              <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
            </svg>
          </span>
          <h2 class="display-3 text-black">Thank you!</h2>
          <p class="lead mb-5">You order was successfuly completed.</p>
          <p><a href="{% url 'app:shop' %}" class="btn btn-sm btn-outline-black">Back to shop</a></p>
        </div>
      </div>
    </div>
  </div>




{% endblock %}